<../../../mkconfig

TARG=\
	canvas.dis\
	control.dis\
	focus.dis\
	form.dis\
	glyph.dis\
	history.dis\
	hit.dis\
	icurses.dis\
	input.dis\
	keymap.dis\
	menu.dis\
	mouse.dis\
	msg.dis\
	paint.dis\
	slider.dis\
	text.dis\
	theme.dis\
	ui.dis\
	view.dis\

MODULES=\

SYSMODULES=\
	icurses/canvas.m\
	icurses/control.m\
	icurses/focus.m\
	icurses/form.m\
	icurses/glyph.m\
	icurses/history.m\
	icurses/hit.m\
	icurses/icurses.m\
	icurses/input.m\
	icurses/keymap.m\
	icurses/menu.m\
	icurses/mouse.m\
	icurses/msg.m\
	icurses/paint.m\
	icurses/slider.m\
	icurses/text.m\
	icurses/theme.m\
	icurses/ui.m\
	icurses/view.m\

DISBIN=$ROOT/dis/lib/icurses

<$ROOT/mkfiles/mkdis

LIMBOFLAGS= -c $LIMBOFLAGS
