<../../../mkconfig

TARG=\
	app.dis\
	appanel.dis\
	bottombar.dis\
	codepage.dis\
	commands.dis\
	config.dis\
	copycmd.dis\
	deletecmd.dis\
	editblock.dis\
	editcmd.dis\
	editcommon.dis\
	editdraw.dis\
	editkeys.dis\
	editor.dis\
	editsearchrun.dis\
	editsource.dis\
	flashlighter.dis\
	fsmodel.dis\
	ic.dis\
	icedit.dis\
	icview.dis\
	input.dis\
	layout.dis\
	mkdircmd.dis\
	modal.dis\
	panelinfo.dis\
	search.dis\
	screen.dis\
	screensaver.dis\
	theme.dis\
	topbar.dis\
	topmenu.dis\
	userdir.dis\
	userstate.dis\
	viewbuttons.dis\
	viewcmd.dis\
	viewcodepage.dis\
	viewer.dis\
	viewgoto.dis\
	viewsearch.dis\
	viewsearchrun.dis\
	viewsource.dis\
	viewstats.dis\
	viewstatus.dis\

MODULES=\

SYSMODULES=\
	ic/app.m\
	ic/appanel.m\
	ic/bottombar.m\
	ic/codepage.m\
	ic/commands.m\
	ic/config.m\
	ic/copycmd.m\
	ic/deletecmd.m\
	ic/editblock.m\
	ic/editcmd.m\
	ic/editcommon.m\
	ic/editdraw.m\
	ic/editkeys.m\
	ic/editor.m\
	ic/editsearchrun.m\
	ic/editsource.m\
	ic/flashlighter.m\
	ic/fsmodel.m\
	ic/input.m\
	ic/layout.m\
	ic/modal.m\
	ic/mkdircmd.m\
	ic/panelinfo.m\
	ic/screen.m\
	ic/screensaver.m\
	ic/search.m\
	ic/state.m\
	ic/theme.m\
	ic/topbar.m\
	ic/topmenu.m\
	ic/userdir.m\
	ic/userstate.m\
	ic/viewbuttons.m\
	ic/viewcmd.m\
	ic/viewcodepage.m\
	ic/viewcommon.m\
	ic/viewer.m\
	ic/viewgoto.m\
	ic/viewsearch.m\
	ic/viewsearchrun.m\
	ic/viewsource.m\
	ic/viewstats.m\
	ic/viewstatus.m\


DISBIN=$ROOT/dis/ic

<$ROOT/mkfiles/mkdis

LIMBOFLAGS= -I$ROOT/module -I$ROOT/module/icurses -I$ROOT/module/ic $LIMBOFLAGS

install:V: all
	rm -f $ROOT/dis/ic/*.dis
	cp *.dis $ROOT/dis/ic
	rm -f $ROOT/dis/ic.dis
	mv $ROOT/dis/ic/ic.dis $ROOT/dis/ic.dis
	rm -f $ROOT/dis/icview.dis
	mv $ROOT/dis/ic/icview.dis $ROOT/dis/icview.dis
	rm -f $ROOT/dis/icedit.dis
	mv $ROOT/dis/ic/icedit.dis $ROOT/dis/icedit.dis

nuke:V: nuke-std
	rm -f $ROOT/dis/ic.dis
	rm -f $ROOT/dis/icview.dis
	rm -f $ROOT/dis/icedit.dis