<../../../mkconfig

TARG=\
	app.dis\
	appanel.dis\
	bottombar.dis\
	commands.dis\
	config.dis\
	copycmd.dis\
	fsmodel.dis\
	ic.dis\
	input.dis\
	layout.dis\
	screen.dis\
	theme.dis\
	topbar.dis\

MODULES=\

SYSMODULES=\
	ic/app.m\
	ic/appanel.m\
	ic/bottombar.m\
	ic/commands.m\
	ic/config.m\
	ic/copycmd.m\
	ic/fsmodel.m\
	ic/input.m\
	ic/layout.m\
	ic/screen.m\
	ic/state.m\
	ic/theme.m\
	ic/topbar.m\

DISBIN=$ROOT/dis/ic

<$ROOT/mkfiles/mkdis

LIMBOFLAGS= -I$ROOT/module -I$ROOT/module/icurses -I$ROOT/module/ic $LIMBOFLAGS

install:V: all
	rm -f $ROOT/dis/ic/*.dis
	cp *.dis $ROOT/dis/ic
	rm -f $ROOT/dis/ic.dis
	mv $ROOT/dis/ic/ic.dis $ROOT/dis/ic.dis

nuke:V: nuke-std
	rm -f $ROOT/dis/ic.dis
